/**
 * Маппинг типов иллюстраций к реальным именам файлов
 * Некоторые иллюстрации имеют суффиксы в именах файлов из-за cropping в Figma
 */
export const illustrationFilenames: Record<string, string> = {
  "something-happened": "something-happened.png",
  "time-slot": "time-slot.png",
  "self-esteem": "self-esteem.png",
  "working-calmly": "working-calmly.png",
  "test": "test-25631f.png",
  "past": "past.png",
  "reactions": "reactions.png",
  "self-help": "self-help.png",
  "take-on-challenges": "take-on-challenges.png",
  "see-a-therapist": "see-a-therapist.png",
  "payment-completed": "payment-completed.png",
  "relax": "relax.png",
  "aggression": "aggression.png",
  "self-knowledge": "self-knowledge.png",
  "thanks-for-feedback": "thanks-for-feedback.png",
  "card-saved": "card-saved.png",
  "self-care": "self-care.png",
  "therapist": "therapist.png",
  "payment-not-processed": "payment-not-processed.png",
  "emotions": "emotions.png",
  "enjoy-life-daily": "enjoy-life-daily.png",
  "want-to-grow": "want-to-grow.png",
  "couch": "couch.png",
  "meditation": "meditation-32d716.png",
  "player": "player.png",
  "burn-out": "burn-out-ec386a.png",
  "aggression-level": "aggression-level-281b92.png",
  "depression": "depression-53ab09.png",
  "type49": "type49-10ed20.png",
  "building": "building-19106c.png",
  "skills": "skills-c7387c.png",
  "heart": "heart-173dea.png",
  "tree": "tree-57ceaf.png",
  "battery": "battery-22df1f.png",
  "relax-meditation": "relax-meditation-676e63.png",
  "clock": "clock-676e63.png",
  "megaphone": "megaphone-2d5ccb.png",
  "stones": "stones.png",
  "before-conversation": "before-conversation-51eebd.png",
  "laptop-fire": "laptop-fire-788001.png",
  "overloaded": "overloaded-1224bd.png",
  "deep-relax": "deep-relax-ee43d6.png",
  "coffee-relax": "coffee-relax-51d854.png",
  "sandclock": "sandclock-2e284c.png",
  "earphones": "earphones-cd54cf.png",
  "hugs-himself": "hugs-himself.png",
  "puzzles": "puzzles-34756d.png",
  "holding-sun": "holding-sun-34756d.png",
  "emotions-level-orange": "emotions-level-orange-185255.png",
  "question": "question-62368f.png",
  "thoughts": "thoughts-54d165.png",
  "party": "party-6c7823.png",
  "okay": "okay-ecf91d.png",
  "phone": "phone-4649bd.png",
  "empty-search": "empty-search-28f844.png",
};
